"""Device Table

Revision ID: 3ced331b0db8
Revises: 63b9da8adb14
Create Date: 2019-11-13 16:41:15.192178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ced331b0db8'
down_revision = '63b9da8adb14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deviceId', sa.String(length=64), nullable=True),
    sa.Column('devicename', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('dept_code', sa.String(length=128), nullable=True),
    sa.Column('device_function', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_deviceId'), 'device', ['deviceId'], unique=True)
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    op.drop_index(op.f('ix_device_deviceId'), table_name='device')
    op.drop_table('device')
    # ### end Alembic commands ###
